version: '3.4'

services:
  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2222:80"

  sale.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "3333:80"

  stock.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "4444:80"
